kind: pipeline
type: docker
name: main

workspace:
  path: /app

environment:
  JWT_ALGORITHM: "HS256"
  JWT_EXPIRE_TIME_MINUTE: 120

  # Application
  APPLICATION_NAME: "application_testing"
  APPLICATION_ENVIRONMENT: "TEST"
  APPLICATION_LOG_LEVEL: "DEBUG"

steps:
  - name: application testing
    image: python:3.9-slim
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
      ENVIRONMENT: TEST
      JWT_SECRET_KEY:
        from_secret: JWT_SECRET_KEY
    commands:
      - pip install --upgrade pip poetry
      - poetry export -f requirements.txt --output requirements.txt --without-hashes --dev
      - pip install --no-cache-dir --upgrade -r requirements.txt
      - chmod +x ./script/service_entrypoint.sh
      - bash ./script/service_entrypoint.sh pytest -p no:warnings

  - name: telegram bot notification
    image: appleboy/drone-telegram
    when:
      status:
        - failure
        - success
    settings:
      token:
        from_secret: Telegram_gggoingdown_CI_bot_token
      to:
        from_secret: Telegram_chat_id
      message: >
        {{#success build.status}}
          Repository: {{repo.name}}
          Version: {{build.number}}
          Commit message:  {{commit.message}}
          Message: Test succeeded. Good job.
        {{else}}
          Repository: {{repo.name}}
          Version: {{build.number}}
          Commit message:  {{commit.message}}
          Message: Test failed. Fix me please.
        {{/success}}

trigger:
  branch:
    - master
    - test/*
    - feature/*

---
kind: pipeline
type: docker
name: build

steps:
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: DockerHub_username
      password:
        from_secret: DockerHub_password
      repo: gggoingdown/fastapi-cookiecutter
      build_args: ENVIRONMENT=PROD
      tags:
        - latest
        - ${DRONE_TAG}
      storage_driver: vfs

  - name: send telegram notification
    image: appleboy/drone-telegram
    when:
      status:
        - success
        - failure
    settings:
      token:
        from_secret: Telegram_gggoingdown_CI_bot_token
      to:
        from_secret: Telegram_chat_id
      message: >
        {{#success build.status}}
          Repository: {{repo.name}}
          Version: {{build.number}}
          Commit message:  {{commit.message}}
          Message: build image succeeded. Good job.
        {{else}}
          Repository: {{repo.name}}
          Version: {{build.number}}
          Commit message:  {{commit.message}}
          Message: build image failed. Fix me please.
        {{/success}}

trigger:
  event:
    - tag
