version: "3.9"
services:
  app:
    container_name: app
    build:
      context: .
    volumes:
      - .:/app/
      - ./log/application:${APPLICATION_LOG_PATH:-/var/log/application}
    restart: unless-stopped
    ports:
      - ${APPLICATION_EXPOSE:-8000}:8000
    expose:
      - ${APPLICATION_EXPOSE:-8000}
    env_file:
      - ./env/.dev.env
    environment:
      - MIGRATION=${MIGRATION?Variable not set}
      - CREATE_INIT_DATA=${CREATE_INIT_DATA?Variable not set}
      - APPLICATION_ENVIRONMENT=${APPLICATION_ENVIRONMENT?Variable not set}
    command:
      [
        "./script/service_entrypoint.sh",
        "uvicorn",
        "app.main:app",
        "--host=0.0.0.0",
        "--port=8000",
        "--reload"
      ]

  worker:
    container_name: worker
    build:
      context: .
    volumes:
      - .:/app/
      - ./log/application:${APPLICATION_LOG_PATH:-/var/log/application}
    restart: unless-stopped
    env_file:
      - ./env/.dev.env
    environment:
      - MIGRATION=false
      - CREATE_INIT_DATA=false
      - APPLICATION_ENVIRONMENT=${APPLICATION_ENVIRONMENT?Variable not set}
    command:
      [
        "./script/service_entrypoint.sh",
        "python",
        "./app/main.py"
      ]
  worker-monitor:
    container_name: worker-monitor
    build:
      context: .
    volumes:
      - .:/app/
      - ./log/application:${APPLICATION_LOG_PATH:-/var/log/application}
    restart: unless-stopped
    env_file:
      - ./env/.dev.env
    environment:
      - MIGRATION=false
      - CREATE_INIT_DATA=false
      - APPLICATION_ENVIRONMENT=${APPLICATION_ENVIRONMENT?Variable not set}
    ports:
      - ${FLOWER_EXPOSE?Variable not set}:5555
    command:
      [
        "celery",
        "-A",
        "app.main.celery",
        "flower",
        "--basic_auth=${FLOWER_USERNAME}:${FLOWER_PASSWORD}"
      ]

  db:
    container_name: db
    image: postgres:13
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME?Variable not set}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - ${POSTGRES_EXPOSE:-5432}:5432
    expose:
      - ${POSTGRES_EXPOSE:-5432}

  cache:
    container_name: cache
    image: redis:6.2
    ports:
      - ${REDIS_EXPOSE:-6379}:6379
    expose:
      - ${REDIS_EXPOSE:-6379}
    restart: unless-stopped
    command: >
      --requirepass ${REDIS_PASSWORD?Variable not set}

  broker:
    image: rabbitmq:3.8-management
    container_name: broker
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME?Variable not set}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD?Variable not set}
    restart: unless-stopped
    ports:
      - ${RABBITMQ_EXPOSE?Variable not set}:5672
      - ${RABBITMQ_MANAGEMENT_EXPOSE?Variable not set}:15672
