version: "3.9"
services:
  app:
    image: app:latest
    container_name: app
    build:
      context: .
    volumes:
      - .:/app/
    restart: unless-stopped
    ports:
      - ${APPLICATION_EXPOSE:-8000}:8000
    expose:
      - ${APPLICATION_EXPOSE:-8000}
    env_file:
      - ./env/.dev.env
    environment:
      - MIGRATION=true
    command:
      [
        "./script/service_entrypoint.sh",
        "uvicorn",
        "app.main:app",
        "--host=0.0.0.0",
        "--port=8000",
        "--reload"
      ]
